#!/usr/bin/env bash
### radgov-cancel -- cancel a proposal
### Usage: radgov cancel <id>
### cancel a given proposal id
set -eu -o pipefail
[[ $# = 1 ]] || (radgov cancel --help && exit 1)

if [[ $(radgov state "$1") == Executed ]]; then
  echo >&2 "Proposal is Executed, cannot cancel"
  exit 1
fi
[[ $ETH_FROM ]] || (echo >&2 "${0##*/}: error: Please set ETH_FROM to your account address" && exit 1)

seth send "$RADGOV" "cancel(uint256)" "$1" --from "$ETH_FROM"
