#!/usr/bin/env bash
### radgov-account -- print rad balance and voting power of the given account
### Usage: radgov account <address>
### Print rad balance and voting power of the given account
set -ex

[[ $# = 1 ]] || (radgov account --help && exit 1)
BAL=$(seth call "$RAD" "balanceOf(address)(uint256)" "$1")
DELEGATE=$(seth call "$RAD" "delegates(address)(address)" "$1")
VOTES=$(seth call "$RAD" "getCurrentVotes(address)(uint96)" "$1")
echo "-- $1 -- "
echo "Holds:        $(seth --to-fix 18 "$BAL") RADICLE"
echo "Voting power: $(seth --to-fix 18 "$VOTES")"
echo "Delegated to: $DELEGATE"
