#!/usr/bin/env bash
### radgov-ls -- list current proposals
### Usage: radgov ls
### List all current proposals
set -eu

N=$(seth call "$RADGOV" "proposalCount()(uint256)")
echo "Listing $N proposals in Governor..."
ID=1
while [ $ID -le "$N" ]
do
  radgov proposal $ID
  echo ""
  ((ID++))
done
