#!/usr/bin/env bash
### radgov-propose -- make a governance proposal
### Usage: radgov propose <proposal>
### Propose a governance call from a file.
set -eu -o pipefail
[[ $# = 1 ]] || (radgov propose --help && exit 1)

description="$(sed -e '/^## ACTIONS ##$/Q' -e 's/"/\\"/g' "$1")"
proposal="$(sed -e '1,/^## ACTIONS ##$/d' -e '/^[[:space:]]*$/d' -e '/```.*/d' "$1")"

targets="[$(cut -f1 -d' ' <<< "$proposal" \
  | xargs -n1 -d'\n' -I % -- sh -c "seth --to-address %" \
  | paste -sd,)]"
values="[$(cut -f2 -d' ' <<< "$proposal" | paste -sd,)]"
sigs="[$(cut -f3 -d' ' <<< "$proposal" | paste -sd,)]"
# allow for non hex calldata
data="[$(cut -f3- -d' ' <<< "$proposal" \
  | xargs -n1 -d'\n' -I % -- sh -c "seth calldata %" \
  | cut -b -2,11- | paste -sd,)]"

targets="$(sed -e 's/\(0x[0-9a-fA-F]*\)/"\1"/g' <<< "$targets")"
data="$(sed -e 's/\(0x[0-9a-fA-F]*\)/"\1"/g' <<< "$data")"

[[ $ETH_FROM ]] || (echo >&2 "${0##*/}: error: Please set ETH_FROM to your account address" && exit 1)

# propose(targets,values,signatures,calldatas,description)
PROPOSE="propose(address[],uint256[],string[],bytes[],string)"
data="$(radgov calldata "$PROPOSE" \
  "$targets" "$values" "$sigs" "$data" \""$description"\")"
seth send "$RADGOV" "$data" --from "$ETH_FROM"
# each address can only have one proposal
seth call "$RADGOV" "latestProposalIds(address)(uint256)" "$ETH_FROM"
