#!/usr/bin/env bash
### radgov-queue -- queue a proposal
### Usage: radgov queue <id>
### queue a given proposal id
set -eu -o pipefail
[[ $# = 1 ]] || (radgov queue --help && exit 1)

if [[ $(radgov state "$1") != Succeeded ]]; then
  echo >&2 "Proposal has not Succeeded, queueing will fail"
  exit 1
fi

[[ $ETH_FROM ]] || (echo >&2 "${0##*/}: error: Please set ETH_FROM to your account address" && exit 1)

seth send "$RADGOV" "queue(uint256)" "$1" --from $ETH_FROM
