#!/usr/bin/env bash
### radgov-propose -- make a governance proposal
### Usage: radgov propose <proposal>
### Propose a governance call from a file.
set -eu -o pipefail
[[ $# = 1 ]] || (radgov propose --help && exit 1)

description="$(sed -e '/^## PROPOSAL ##$/Q' -e 's/"/\\"/g' "$1")"
proposal="$(sed -e '1,/^## PROPOSAL ##$/d' -e '/^[[:space:]]*$/d' -e '/```.*/d' "$1")"

targets="[$(cut -f1 -d' ' <<< "$proposal" | paste -sd,)]"
values="[$(cut -f2 -d' ' <<< "$proposal" | paste -sd,)]"
sigs="[$(cut -f3 -d' ' <<< "$proposal" | paste -sd,)]"
# allow for non hex calldata
data="[$(cut -f3- -d' ' <<< "$proposal" \
  | xargs -n1 -d'\n' -I % -- sh -c "seth calldata %" \
  | cut -b -2,11- | paste -sd ',')]"

# propose(targets,values,signatures,calldatas,description)
PROPOSE="propose(address[],uint256[],string[],bytes[],string)"
seth send "$RADGOV" "$PROPOSE" \
  "$targets" "$values" "$sigs" "$data" \""$description"\"
# each address can only have one proposal
seth call "$RADGOV" "latestProposalIds(address)(uint256)"
